/**
 * Generated by Gas3 v2.3.1 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.wineshop.admin.entities {

	import mx.collections.ArrayCollection;

    [Bindable]
    [RemoteClass(alias="com.wineshop.admin.entities.Domaine")]
    public class Domaine extends DomaineBase {
    	
		public function Domaine():void {
			vins = new ArrayCollection();
		}
    }
}