/**
 * Generated by Gas3 v2.3.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.wineshop.admin.entities {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.wineshop.admin.entities.Vin$Type")]
    public class Vin$Type extends Enum {

        public static const ROUGE:Vin$Type = new Vin$Type("ROUGE", _);
        public static const BLANC:Vin$Type = new Vin$Type("BLANC", _);
        public static const ROSE:Vin$Type = new Vin$Type("ROSE", _);

        function Vin$Type(value:String = null, restrictor:* = null) {
            super((value || ROUGE.name), restrictor);
        }

        protected override function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [ROUGE, BLANC, ROSE];
        }

        public static function valueOf(name:String):Vin$Type {
            return Vin$Type(ROUGE.constantOf(name));
        }
    }
}