/**
 * Generated by Gas3 v2.3.1 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.wineshop.admin.entities {

    [Bindable]
    [RemoteClass(alias="com.wineshop.admin.entities.Vin")]
    public class Vin extends VinBase {
    	
		public function Vin(domaine:Domaine = null):void {
			this.domaine = domaine;
			this.annee = 2011;
			this.type = Vin$Type.ROUGE;
		}
    }
}