/**
 * Generated by Gas3 v2.3.1 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.wineshop.admin.entities {

    [Bindable]
    [RemoteClass(alias="com.wineshop.admin.entities.Welcome")]
    public class Welcome extends WelcomeBase {
    }
}