/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.wineshop.admin.client.entities {

    [Bindable]
    [RemoteClass(alias="com.wineshop.admin.entities.Address")]
    public class Address extends AddressBase {

        public function Address() {
            super();
        }
    }
}