/**
 * Generated by Gas3 v2.3.1 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.wineshop.admin.services {

    [RemoteClass(alias="com.wineshop.admin.services.DomaineService")]
    public class DomaineService extends DomaineServiceBase {
    }
    
}
