/**
 * Generated by Gfx v2.3.2 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.wineshop.admin.client.entities;

import org.granite.messaging.amf.RemoteClass;

@RemoteClass("com.wineshop.admin.entities.Wine$Type")
public enum Wine$Type {

    RED, 
    WHITE, 
    ROSE
}
